//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperCopa.Modelagem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atleta : Agente
    {
        public Nullable<decimal> Altura { get; set; }
        public string PosicaoPrincipal { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
    }
}
