//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperCopa.Modelagem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipe
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public int Treinador_Id { get; set; }
    
        public virtual Treinador Treinador { get; set; }
    }
}
